CREATE OR REPLACE PROCEDURE CALC_CGPA(
    V_STUDENT_ID NUMBER
) IS
    V_SUM_GPA          NUMBER(4, 2);
    V_DEPARTMENT_ID    NUMBER(4);
    V_SEMESTER         NUMBER(2);
    V_SUM_CREDIT_HOURS NUMBER(5);
BEGIN
    SELECT
        SEMESTER,
        DEPARTMENT_ID INTO V_SEMESTER,
        V_DEPARTMENT_ID
    FROM
        STUDENTS
    WHERE
        STUDENT_ID = V_STUDENT_ID;
 
    SELECT
        (SUM(NVL(E.QUALITY_POINTS, 0))/ SUM(NVL(c.CREDIT_HOURS, 0))) INTO V_SUM_GPA
    FROM
        ENROLLMENT E
        INNER JOIN COURSES C
        ON E.COURSE_ID = C.COURSE_ID
    WHERE
        E.STUDENT_ID = V_STUDENT_ID
        AND C.SEMESTER = V_SEMESTER
        AND C.DEPARTMENT_ID = V_DEPARTMENT_ID;
    UPDATE STUDENTS
    SET
        GPA = V_SUM_GPA
    WHERE
        STUDENT_ID = V_STUDENT_ID;
END;