CREATE OR REPLACE FUNCTION CHECK_PK_NO(
    V_PK_COL OUT VARCHAR2,
    V_TABLE_NAME IN VARCHAR2, V_OWNER IN VARCHAR2
) RETURN NUMBER IS
    V_PK_COUNT NUMBER(2);
    V_PK_TYPE  VARCHAR2(20);
BEGIN
    SELECT
        COUNT(COLS.COLUMN_NAME) INTO V_PK_COUNT
    FROM
        ALL_CONSTRAINTS CONS,
        ALL_CONS_COLUMNS COLS
    WHERE
        CONS.CONSTRAINT_TYPE = 'P'
        AND CONS.OWNER = V_OWNER
        AND CONS.CONSTRAINT_NAME = COLS.CONSTRAINT_NAME
        AND COLS.TABLE_NAME = V_TABLE_NAME;
    IF V_PK_COUNT = 1 THEN
        SELECT
            COLS.COLUMN_NAME INTO V_PK_COL
        FROM
            ALL_CONSTRAINTS CONS,
            ALL_CONS_COLUMNS COLS
        WHERE
            CONS.CONSTRAINT_TYPE = 'P'
            AND CONS.OWNER = V_OWNER
            AND CONS.CONSTRAINT_NAME = COLS.CONSTRAINT_NAME
            AND COLS.TABLE_NAME = V_TABLE_NAME;
        SELECT
            DATA_TYPE INTO V_PK_TYPE
        FROM
            USER_TAB_COLUMNS
        WHERE
            TABLE_NAME = V_TABLE_NAME
            AND COLUMN_NAME = V_PK_COL;
        IF V_PK_TYPE = 'NUMBER' THEN
            RETURN V_PK_COUNT;
        ELSE
            V_PK_COUNT := 5;
            V_PK_COL := 'NOT NUMBER';
            RETURN V_PK_COUNT;
        END IF;
    ELSE
        V_PK_COL := '0 OR MORE THAN 1 COLUMN';
        RETURN V_PK_COUNT;
    END IF;
END;