CREATE OR REPLACE TRIGGER POINTS_TRIGGER BEFORE
    INSERT OR UPDATE OF GRADE ON ENROLLMENT FOR EACH ROW
DECLARE
    V_CREDIT_H  NUMBER(2);

BEGIN
    CASE :NEW.GRADE
        WHEN 'A' THEN
            :NEW.POINTS := 4;
        WHEN 'B' THEN
            :NEW.POINTS := 3;
        WHEN 'C' THEN
            :NEW.POINTS := 2;
        WHEN 'D' THEN
            :NEW.POINTS := 1;
        ELSE
            :NEW.POINTS := 0;
    END CASE;

    SELECT
        CREDIT_HOURS INTO V_CREDIT_H
    FROM
        COURSES
    WHERE
        COURSE_ID = :NEW.COURSE_ID;
    :NEW.QUALITY_POINTS := :NEW.POINTS*V_CREDIT_H;

END;