CREATE OR REPLACE PROCEDURE CREATE_SEQ(V_COL_NAME VARCHAR2, V_TABLE_NAME VARCHAR2)
IS
    V_START NUMBER(7):=0;
BEGIN
    EXECUTE IMMEDIATE 'SELECT NVL(MAX('|| V_COL_NAME ||'), 0)+1 FROM '||V_TABLE_NAME INTO V_START;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE '||V_TABLE_NAME||'_SEQ'||' START WITH '||V_START||
                        ' MAXVALUE 999999999999999999999999999 INCREMENT BY 1';
                    
END;
