create or REPLACE PROCEDURE DROP_SEQ_PROCEDURE IS
    CURSOR V_SEQ_CURSOR is 
    SELECT * from USER_SEQUENCES;
BEGIN
for V_SEQ_RECORD IN V_SEQ_CURSOR LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE '||V_SEQ_RECORD.SEQUENCE_NAME||'';
end LOOP;
END;